default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: player_development

test:
  <<: *default
  database: player_test

production:
  <<: *default
  database: player_production
  username: player_backend
  password: <%= ENV["EVERBEE_STORE_BACKEND_DATABASE_PASSWORD"] %>
